- name: Ensure tenant customer-xyz exists
  aci_tenant:
    host: sandboxapicdc.cisco.com
    username: admin
    password: ciscopsdt

    tenant: customer-xyz
    description: Customer XYZ
    state: present
