  tasks:
  - name: Add a new EPG
    cisco.aci.aci_epg:
      tenant: production
      ap: intranet
      epg: web_epg
      description: Web Intranet EPG
      bd: prod_bd
    delegate_to: localhost
